version: "3"

services:
  selenium-hub:
    image: selenium/hub
    container_name: "${PROJECT_NAME}_web-automation_selenium-hub"
    ports:
      - "${BIND_IP:-127.0.0.1}:4444:4444"

    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 3000
      GRID_TIMEOUT: 3000
    networks:
      - "${PROJECT_NAME}"
  selenium-chrome:
    image: selenium/node-chrome
    container_name: "${PROJECT_NAME}_web-automation_chrome"
    depends_on:
      - selenium-hub
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 4
      NODE_MAX_INSTANCES: 4
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "${BIND_IP:-127.0.0.1}:9001:5900"
    links:
      - selenium-hub
    networks:
      - "${PROJECT_NAME}"
  selenium-firefox:
    image: selenium/node-firefox
    container_name: "${PROJECT_NAME}_web-automation_firefox"
    depends_on:
      - selenium-hub
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 2
      NODE_MAX_INSTANCES: 2
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "${BIND_IP:-127.0.0.1}:9002:5900"
    links:
      - selenium-hub
    networks:
      - "${PROJECT_NAME}"
